<?php
// ÜRETİLDİ: tools/build.mjs — elle düzenlemeler bir sonraki üretimde ezilir (açıklamalar hariç: bkz. inc/meta.php başı)
return [[
    'yol' => '/eroin-bagimliligi/',
    'baslik' => 'Eroin Bağımlılığı',
    'tarih' => '2022-03-26T12:55:03+00:00',
    'tarihTr' => '26 Mart 2022',
    'gorsel' => '/wp-content/uploads/2022/03/AdobeStock_210694690-scaled-1.jpeg',
    'ozet' => 'Bağımlılık, kişinin fiziksel ve psikolojik birçok zarar görmesine rağmen bağımlısı olduğu maddeyi kullanması, kendinde yol açtığı sıkıntılara karşı bu maddeden…',
    'kategori' => 'Sağlık',
  ], [
    'yol' => '/eroin-nedir/',
    'baslik' => 'Eroin Nedir?',
    'tarih' => '2022-03-26T12:38:47+00:00',
    'tarihTr' => '26 Mart 2022',
    'gorsel' => '/wp-content/uploads/2022/03/bg-2.jpg',
    'ozet' => 'Eroin ilk olarak Londra’da bir İngiliz kimyacı tarafından sentezlenmiştir. O zamanlarda morfin çeşitli asitler ile birleştirilerek çeşitli deneyler yapılmaktaydı.',
    'kategori' => 'Sağlık',
  ], [
    'yol' => '/opiatlar-nedir/',
    'baslik' => 'Opiatlar Nedir?',
    'tarih' => '2022-03-26T12:30:20+00:00',
    'tarihTr' => '26 Mart 2022',
    'gorsel' => '/wp-content/uploads/2022/03/61fa241ad265a211742e9f29.jpg',
    'ozet' => 'Opiatlar dilimizde Opiyatlar olarak da adlandırılmaktadır. Opiyatlar merkezi sinir sistemini üzerinde depresan olarak etki gösteren narkotik ilaçlardır.',
    'kategori' => 'Sağlık',
  ], [
    'yol' => '/kokain-bagimliligi-tedavisi/',
    'baslik' => 'Kokain Bağımlılığı Tedavisi',
    'tarih' => '2022-03-26T12:20:37+00:00',
    'tarihTr' => '26 Mart 2022',
    'gorsel' => '/wp-content/uploads/2022/03/bagimlilik-tedavi-hekim-terapi-madde-danismanlik-1024x1024-1.jpg',
    'ozet' => 'Bağımlılık alkol, uyuşturucu veya uyarıcı bir maddenin kişiye fiziksel, ruhsal ve sosyal sorunlara yol açmasına rağmen kişinin bu maddeleri kullanmaya devam etmesi…',
    'kategori' => 'Sağlık',
  ], [
    'yol' => '/uyusturucu-testi-nedir/',
    'baslik' => 'Uyuşturucu Testi Nedir?',
    'tarih' => '2022-03-19T20:15:37+00:00',
    'tarihTr' => '19 Mart 2022',
    'gorsel' => '/wp-content/uploads/2022/03/csm_content_mpu_test_9d23debc60.jpg',
    'ozet' => 'Günümüzde uyuşturucu testi bir hayli artmış ve artmaya devam etmektedir. Bu sebeple aileler uyuşturucu veya uyarıcı madde kullanan veya şüphelendikleri yakınları için…',
    'kategori' => 'Sağlık',
  ], [
    'yol' => '/kokain-bagimliligi/',
    'baslik' => 'Kokain Bağımlılığı',
    'tarih' => '2022-03-15T15:51:16+00:00',
    'tarihTr' => '15 Mart 2022',
    'gorsel' => '/wp-content/uploads/2022/03/What-Are-the-Worlds-Most-Dangerous-Drugs.jpg',
    'ozet' => 'Kokain uyuşturucu ve uyarıcı maddeler arasında en fazla bağımlılık yapan ve en tehlikeli olan uyarıcı maddelerden biridir.',
    'kategori' => 'Sağlık',
  ], [
    'yol' => '/kokain-nedir/',
    'baslik' => 'Kokain Nedir?',
    'tarih' => '2022-03-09T14:30:31+00:00',
    'tarihTr' => '9 Mart 2022',
    'gorsel' => '/wp-content/uploads/2022/03/cocaineaddiction.jpg',
    'ozet' => 'Kokain bilinen bir diğer ismi ile benzoylemetil ekgonin, Güney Amerikada yetişen koka bitkisinin yapraklarında elde edilmektedir.',
    'kategori' => 'Sağlık',
  ], [
    'yol' => '/uyarici-madde-nedir/',
    'baslik' => 'Uyarıcı Madde Nedir?',
    'tarih' => '2022-03-03T10:51:20+00:00',
    'tarihTr' => '3 Mart 2022',
    'gorsel' => '/wp-content/uploads/2022/03/amphetamine-v-methampheta.jpg',
    'ozet' => 'Uyuşturucu kullanımı günümüzün en büyük sorunlarından biri haline gelmiştir. Her geçen gün artarak devam eden bu sorun yetişkin bireyleri, gençleri ve çocukları içine…',
    'kategori' => 'Sağlık',
  ], [
    'yol' => '/esrar-bagimliligi-tedavisi/',
    'baslik' => 'Esrar Bağımlılığı Tedavisi',
    'tarih' => '2022-03-02T13:39:30+00:00',
    'tarihTr' => '2 Mart 2022',
    'gorsel' => '/wp-content/uploads/2022/03/ot.jpg',
    'ozet' => 'Esrar, kenevir bitkisinin kurutulmuş yaprak ve çiçeklerinden elde edilen bir uyuşturucu madde çeşididir.',
    'kategori' => 'Sağlık',
  ], [
    'yol' => '/esrar-bagimliligi/',
    'baslik' => 'Esrar Bağımlılığı',
    'tarih' => '2022-03-02T11:00:34+00:00',
    'tarihTr' => '2 Mart 2022',
    'gorsel' => '/wp-content/uploads/2022/03/104607917_gettyimages-1052403286.jpg',
    'ozet' => 'Esrar günümüzde en çok kullanılan uyuşturucu maddedir. Ülkemizde esrar olarak bilinen bu madde başka ülkelerde maijuana (bitkisel cannabis) olarak bilinmektedir.',
    'kategori' => 'Sağlık',
  ], [
    'yol' => '/esrar-nedir/',
    'baslik' => 'Esrar Nedir?',
    'tarih' => '2022-03-02T09:24:44+00:00',
    'tarihTr' => '2 Mart 2022',
    'gorsel' => '/wp-content/uploads/2022/03/d-1-750x500-1.jpg',
    'ozet' => 'Günümüzde uyuşturucu madde bağımlılığı her geçen gün artmaktadır. Esrar ise dünyada en çok kullanılan uyuşturucu maddelerin başında gelmektedir.',
    'kategori' => 'Sağlık',
  ], [
    'yol' => '/trafik-guvenligini-tehlikeye-sokma-sucu/',
    'baslik' => 'Trafik Güvenliğini Tehlikeye Sokma Suçu',
    'tarih' => '2022-03-01T15:47:37+00:00',
    'tarihTr' => '1 Mart 2022',
    'gorsel' => '/wp-content/uploads/2022/03/Incidente-stradale-sotto-effetto-di-stupefacenti.jpg',
    'ozet' => 'Günümüzde araç kullanımının yaygınlaşması ile birlikte pek çok kaza meydana gelmektedir. Bu kazaların büyük bir çoğunluğu alkollü araç kullanmaktan kaynaklanmaktadır.',
    'kategori' => 'Sağlık',
  ], [
    'yol' => '/alkolmetre-nedir/',
    'baslik' => 'Alkolmetre Nedir?',
    'tarih' => '2022-02-25T13:35:06+00:00',
    'tarihTr' => '25 Şubat 2022',
    'gorsel' => '/wp-content/uploads/2022/02/TorontoDUI__Apr_17_post_upd.jpg.500x333_q85_crop.jpg',
    'ozet' => 'Kandaki alkol oranını ölçen cihazlara alkolmetre adı verilir. Kandaki alkol miktarını belirten ölçü birime ise ‘promil’ adı verilmektedir.',
    'kategori' => 'Sağlık',
  ], [
    'yol' => '/uyusturucu-madde-testi/',
    'baslik' => 'Uyuşturucu Madde Testi',
    'tarih' => '2022-02-22T10:47:21+00:00',
    'tarihTr' => '22 Şubat 2022',
    'gorsel' => '/wp-content/uploads/2022/02/closeup-shot-white-pills-glass-dish-lab.jpg',
    'ozet' => 'Uyuşturucu madde testi bir diğer adıyla drug test olarak bilinmektedir. Uyuşturucu madde testleri kişinin yeşil reçeteli bir ilaca veya uyuşturucu bir madde alıp…',
    'kategori' => 'Sağlık',
  ], [
    'yol' => '/ergenlerde-uyusturucu-kullanimi/',
    'baslik' => 'Ergenlerde Uyuşturucu Kullanımı',
    'tarih' => '2022-02-18T09:10:31+00:00',
    'tarihTr' => '18 Şubat 2022',
    'gorsel' => '/wp-content/uploads/2022/02/man-overdosed-with-medicine-2.jpg',
    'ozet' => 'Bağımlılık; Bir uyuşturucu maddenin kişi üzerinde fiziksel, ruhsal, ekonomik ve sosyal sorunlara yol açmasına rağmen, madde alımının yapılması, bırakma arzusuna karşılık…',
    'kategori' => 'Sağlık',
  ], [
    'yol' => '/alkol-bagimliligi/',
    'baslik' => 'ALKOL BAĞIMLILIĞI',
    'tarih' => '2022-02-16T11:18:18+00:00',
    'tarihTr' => '16 Şubat 2022',
    'gorsel' => '/wp-content/uploads/2022/02/tired-young-businessman-drinking.jpg',
    'ozet' => 'Alkol insanların hayatına girmesi milattan önceki yıllar dayanmaktadır. Alkollü içeceklerin tam olarak hangi tarihte bulunduğu bilinmemektedir fakat bilinen verilere…',
    'kategori' => 'Sağlık',
  ], [
    'yol' => '/alkollu-arac-kullanmak/',
    'baslik' => 'Alkollü Araç Kullanmak',
    'tarih' => '2022-02-16T08:23:48+00:00',
    'tarihTr' => '16 Şubat 2022',
    'gorsel' => '/wp-content/uploads/2022/02/dangerous-female-driver.jpg',
    'ozet' => 'Alkollü araç kullanmak günümüzde trafik kazalarının büyük bir çoğunluğuna sebebiyet vermektedir.',
    'kategori' => 'Sağlık',
  ], [
    'yol' => '/madde-bagimliligi-tedavisi/',
    'baslik' => 'Madde Bağımlılığı Tedavisi',
    'tarih' => '2022-02-15T16:42:21+00:00',
    'tarihTr' => '15 Şubat 2022',
    'gorsel' => '/wp-content/uploads/2022/02/flat-lay-pills-jar.jpg',
    'ozet' => 'Uyuşturucu maddeler Dünya Sağlık Örgütü Tarafından ‘sağlık için kullanılanlar dışında, yaşayan organizmada kullanıldığında, organizmanın bir veya birden fazla yetisini…',
    'kategori' => 'Sağlık',
  ], [
    'yol' => '/promil-nedir/',
    'baslik' => 'Promil Nedir?',
    'tarih' => '2022-02-15T15:07:40+00:00',
    'tarihTr' => '15 Şubat 2022',
    'gorsel' => '/wp-content/uploads/2022/02/Aday-surucu-alkollu-arac-kullanma-cezasi-1-700x470-1.jpg',
    'ozet' => 'Promil, latince kökenli bir kelime olup promille kelimesinden gelmektedir ve dilimizde Promil olarak nitelendirilmektedir.',
    'kategori' => 'Sağlık',
  ], [
    'yol' => '/madde-bagimliligi-nedir/',
    'baslik' => 'Madde Bağımlılığı Nedir?',
    'tarih' => '2022-02-15T13:43:16+00:00',
    'tarihTr' => '15 Şubat 2022',
    'gorsel' => '/wp-content/uploads/2022/02/pills-stethoscope-syringe.jpg',
    'ozet' => 'Bağımlılık TDK‘ya göre ‘bağımlı olma durumu’ olarak tanımlanmaktadır. Bağımlılık; Herhangi bir uyuşturucu maddenin ruhsal, fiziksel ya da sosyal sorunlara yol açmasına…',
    'kategori' => 'Sağlık',
  ], [
    'yol' => '/ekstazi-nedir/',
    'baslik' => 'Ekstazi Nedir?',
    'tarih' => '2022-01-31T09:28:14+00:00',
    'tarihTr' => '31 Ocak 2022',
    'gorsel' => '/wp-content/uploads/2022/01/60894852_2113963838716411_3978326419854852096_n.jpg',
    'ozet' => '3,4-metilenedioksi-N-metilamfetamin (MDMA) veya bilinen adlarıyla ekstazi, XTC, X, bir tür psikoaktif madde. Kimyasal formülü C11H15NO2 şeklindedir.',
    'kategori' => 'Sağlık',
  ], [
    'yol' => '/metamfetamin-nedir/',
    'baslik' => 'Metamfetamin Nedir?',
    'tarih' => '2022-01-31T09:22:12+00:00',
    'tarihTr' => '31 Ocak 2022',
    'gorsel' => '/wp-content/uploads/2022/01/kapak_103737.jpg',
    'ozet' => 'Metamfetamin (kristal meth); uyarıcı ve halüsinasyon özelliği olan sentetik bir maddedir. Birçok uyarıcı gibi, 6-24 saat süren güçlü bir öfori; dolayısıyla bağımlılık…',
    'kategori' => 'Sağlık',
  ], [
    'yol' => '/amfetamin-nedir/',
    'baslik' => 'Amfetamin Nedir?',
    'tarih' => '2022-01-31T09:17:16+00:00',
    'tarihTr' => '31 Ocak 2022',
    'gorsel' => '/wp-content/uploads/2022/01/amfetamin-nedir-amdetamin-ne-icin-kullanilir-amfetamin-kullanmak-suc-mu.jpg',
    'ozet' => 'Amfetamin (alfa-metil-fenetilamin) narkolepsi ve dikkat eksikliği ve hiperaktivite bozukluğu dahil çeşitli bozuklukların tedavisinde, kilo kontrolünde, iştah azaltıcı…',
    'kategori' => 'Sağlık',
  ]];
