<?php
// ÜRETİLDİ: tools/build.mjs — elle düzenlemeler bir sonraki üretimde ezilir (açıklamalar hariç: bkz. inc/meta.php başı)
return [
  '/' => [
    'title' => 'Anasayfa - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Armas Elektronik yetkili bayi ve servisi Egefe: alkolmetre satış, bakım ve kalibrasyon; CROM TEST uyuşturucu test kitleri; tıbbi cihaz, ÜTS ve Sağlık Bakanlığı danışmanlığı.',
    'h1' => 'Anasayfa',
    'ust' => null,
    'og' => '/wp-content/uploads/2022/01/faceb.jpg',
    'ogType' => 'website',
    'yayin' => '2019-04-01T10:22:07+00:00',
    'guncel' => '2023-08-21T12:42:30+00:00',
  ],
  '/iletisim/' => [
    'title' => 'İletişim - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Egefe iletişim bilgileri: Çankaya/Ankara merkez ofis adresi, telefon, e-posta ve iletişim formu. Formumuz ile bize 7/24 ulaşabilirsiniz.',
    'h1' => 'İletişim',
    'ust' => null,
    'og' => '/wp-content/uploads/2022/01/iletiisimkapak.jpg',
    'ogType' => 'website',
    'yayin' => null,
    'guncel' => null,
  ],
  '/hizmetler/' => [
    'title' => 'Hizmetler - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Alkolmetreler için yetkili servis: arıza ve onarım, periyodik bakım ve kalibrasyon hizmetleri.',
    'h1' => 'Servis Hizmetleri',
    'ust' => null,
    'og' => '/img/urun/nam19-saha.webp',
    'ogType' => 'website',
    'yayin' => '2019-04-01T10:25:28+00:00',
    'guncel' => '2022-01-21T10:56:21+00:00',
  ],
  '/danismanlik/' => [
    'title' => 'Danışmanlık - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'ÜTS, tıbbi cihaz, Sağlık Bakanlığı işlemleri, permi, CE teknik dosya, takviye edici gıda ve kontrol belgesi süreçlerinde sektörel danışmanlık.',
    'h1' => 'Danışmanlık',
    'ust' => null,
    'og' => '/wp-content/uploads/2017/04/blog-post-04.jpg',
    'ogType' => 'website',
    'yayin' => '2022-01-12T09:29:49+00:00',
    'guncel' => null,
  ],
  '/ilac/' => [
    'title' => 'İlaç - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'İlaç danışmanlığı: ilaç ruhsatlandırma, varyasyon ve fiyatlandırma başvuruları, KÜB/KT, okunabilirlik testi ve GMP başvurusu süreçleri.',
    'h1' => 'İlaç',
    'ust' => '/danismanlik/',
    'og' => '/wp-content/uploads/2019/04/blog-post-18.jpg',
    'ogType' => 'website',
    'yayin' => '2022-01-12T09:31:48+00:00',
    'guncel' => '2022-01-12T09:32:14+00:00',
  ],
  '/uts/' => [
    'title' => 'ÜTS - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'ÜTS (Ürün Takip Sistemi) danışmanlığı: kozmetik firma kaydı, sorumlu teknik eleman, kozmetik ürün bildirimi, ÜTS bilgi güncelleme ve tıbbi cihaz ÜTS geçişi.',
    'h1' => 'ÜTS',
    'ust' => '/danismanlik/',
    'og' => '/wp-content/uploads/2022/01/utsbackground.jpg',
    'ogType' => 'website',
    'yayin' => '2022-01-12T09:30:33+00:00',
    'guncel' => '2022-01-20T17:22:18+00:00',
  ],
  '/tibbi-cihaz/' => [
    'title' => 'Tıbbi Cihaz - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Tıbbi cihaz danışmanlığı: UBB/TİTUBB firma kaydı, firma bilgileri güncelleme, UBB e-imza, tıbbi cihaz belge kaydı ve etiket düzenleme işlemleri.',
    'h1' => 'Tıbbi Cihaz',
    'ust' => '/danismanlik/',
    'og' => '/wp-content/uploads/2019/04/blog-post-18.jpg',
    'ogType' => 'website',
    'yayin' => '2022-01-19T08:43:31+00:00',
    'guncel' => null,
  ],
  '/saglik-bakanligi-islemleri/' => [
    'title' => 'Sağlık Bakanlığı İşlemleri - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Sağlık Bakanlığı işlemleri: ilaç ruhsatlandırma, varyasyon, fiyatlandırma, biyosidal ruhsatlandırma, GMP başvurusu, KÜB/KT ve okunabilirlik testi.',
    'h1' => 'Sağlık Bakanlığı İşlemleri',
    'ust' => '/danismanlik/',
    'og' => '/wp-content/uploads/2019/04/blog-post-18.jpg',
    'ogType' => 'website',
    'yayin' => '2022-01-19T09:29:17+00:00',
    'guncel' => '2022-01-19T09:31:57+00:00',
  ],
  '/diger-hizmetler/' => [
    'title' => 'Diğer Hizmetler - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Permi belgesi, CE teknik dosya hazırlanması, takviye edici gıda ve kontrol belgesi başvurularında danışmanlık hizmeti.',
    'h1' => 'Diğer Hizmetler',
    'ust' => '/danismanlik/',
    'og' => '/wp-content/uploads/2019/04/blog-post-18.jpg',
    'ogType' => 'website',
    'yayin' => '2022-01-19T10:14:42+00:00',
    'guncel' => '2022-01-19T10:16:43+00:00',
  ],
  '/blog/' => [
    'title' => 'Blog - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Madde bağımlılığı, uyuşturucu testleri, alkolmetre ve promil hakkında Egefe blog yazıları.',
    'h1' => 'Blog',
    'ust' => null,
    'og' => '/wp-content/uploads/2022/01/123465.jpg',
    'ogType' => 'website',
    'yayin' => null,
    'guncel' => null,
  ],
  '/category/saglik/' => [
    'title' => 'Sağlık - Egefe Sağlık Bilişim A.Ş.',
    'desc' => '',
    'h1' => 'Sağlık',
    'ust' => '/blog/',
    'og' => '/wp-content/uploads/2022/01/faceb.jpg',
    'ogType' => 'website',
    'yayin' => null,
    'guncel' => null,
  ],
  '/hakkimizda/' => [
    'title' => 'Hakkımızda - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Yenilikçi vizyonu ile teknolojinin trendlerini sağlık sektöründe öne çıkaran Egefe, 2017 yılında kurulmuştur; yurt içinde ve yurt dışında hizmet vermektedir.',
    'h1' => 'Hakkımızda',
    'ust' => null,
    'og' => '/wp-content/uploads/2017/04/blog-post-05.jpg',
    'ogType' => 'website',
    'yayin' => null,
    'guncel' => null,
  ],
  '/hizmet-politikamiz/' => [
    'title' => 'Hizmet Politikamız - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Erişilebilirlik: Şirketimiz tarafından sunulan çeşitli iletişim kanallarıyla müşterilerimiz şikayetlerini, bilgi taleplerini, öneri ya da memnuniyetlerini…',
    'h1' => 'Hizmet Politikamız',
    'ust' => null,
    'og' => '/wp-content/uploads/2017/04/blog-post-14.jpg',
    'ogType' => 'website',
    'yayin' => '2019-04-01T10:15:58+00:00',
    'guncel' => '2022-01-20T12:50:56+00:00',
  ],
  '/kalite-politikamiz/' => [
    'title' => 'Kalite Politikamız - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Sadece kaliteli, akredite kuruluşlar tarafından onaylı, yasal koşulları tam olarak sağlayan, Egefe kalite prosedürlerine uygun, sağlıklı ve güvenli…',
    'h1' => 'Kalite Politikamız',
    'ust' => null,
    'og' => '/wp-content/uploads/2017/04/blog-post-14.jpg',
    'ogType' => 'website',
    'yayin' => '2022-01-12T08:11:32+00:00',
    'guncel' => '2022-01-20T12:47:05+00:00',
  ],
  '/kariyer/' => [
    'title' => 'Kariyer - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Egefe insan kaynakları politikası, adil, şeffaf ve söz hakkı tanıyan, çalışanların potansiyellerini ortaya koyma fırsatları bulduğu, her bir çalışanın…',
    'h1' => 'Kariyer',
    'ust' => null,
    'og' => '/wp-content/uploads/2022/01/2003974.jpg',
    'ogType' => 'website',
    'yayin' => '2019-04-01T10:20:18+00:00',
    'guncel' => '2022-01-20T12:37:27+00:00',
  ],
  '/bilgi/' => [
    'title' => 'Bilgi - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Periyodik bakım, teknik servisteki cihazın durumu, yedek parça temini ve NAM-07/NAM-19 cihazları hakkında sık sorulan sorular.',
    'h1' => 'Bilgi',
    'ust' => null,
    'og' => '/wp-content/uploads/2017/04/blog-post-04.jpg',
    'ogType' => 'website',
    'yayin' => '2019-04-01T10:20:56+00:00',
    'guncel' => '2022-02-04T12:31:34+00:00',
  ],
  '/ariza-ve-onarim/' => [
    'title' => 'Arıza ve Onarım - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'NAM-07 ve NAM-19 cihazlarının ve yedek parçalarının arızi bakımlarını üstleniyoruz. Ürününüzün garantisi devam ederken; ürününüzde herhangi bir arıza…',
    'h1' => 'Arıza ve Onarım',
    'ust' => '/hizmetler/',
    'og' => '/wp-content/uploads/2023/08/egefeback1.jpg',
    'ogType' => 'website',
    'yayin' => '2019-04-01T10:28:28+00:00',
    'guncel' => '2023-08-03T10:20:08+00:00',
  ],
  '/periyodik-bakim/' => [
    'title' => 'Periyodik Bakım - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Satışını ve bakımlarını yaptığımız Alkolmetrelerin belirlenmiş periyotlar dahilinde bakımları yapılmaktadır.',
    'h1' => 'Periyodik Bakım',
    'ust' => '/hizmetler/',
    'og' => '/wp-content/uploads/2023/08/egefeback1.jpg',
    'ogType' => 'website',
    'yayin' => '2022-01-12T09:04:28+00:00',
    'guncel' => '2023-08-03T10:15:59+00:00',
  ],
  '/kalibrasyon/' => [
    'title' => 'Kalibrasyon - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Kalibrasyon işleminde, ölçmede kullanılan test-ölçü aleti veya cihazlarının sapmaları belirlenir, hataları düzeltilir.',
    'h1' => 'Kalibrasyon',
    'ust' => '/hizmetler/',
    'og' => '/wp-content/uploads/2023/08/egefeback1.jpg',
    'ogType' => 'website',
    'yayin' => '2022-01-12T09:04:56+00:00',
    'guncel' => '2023-08-03T10:15:28+00:00',
  ],
  '/uts/kozmetik-firma-kaydi/' => [
    'title' => 'Kozmetik Firma Kaydı - Egefe Sağlık Bilişim A.Ş.',
    'desc' => '5324 sayılı Kozmetik Kanunu gereğince kozmetik ürünlerin piyasaya arz edilmeden önce Bakanlığa bildiriminin yapılması zorunludur.',
    'h1' => 'Kozmetik Firma Kaydı',
    'ust' => '/uts/',
    'og' => '/wp-content/uploads/2022/01/utsbackground-1.jpg',
    'ogType' => 'website',
    'yayin' => '2022-01-13T18:37:01+00:00',
    'guncel' => '2022-01-20T19:40:51+00:00',
  ],
  '/uts/sorumlu-teknik-eleman/' => [
    'title' => 'Sorumlu Teknik Eleman - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Eczacı veya kozmetik alanında iki yıl fiilen çalışmış olduğunu belgelemek kaydıyla kimyager, biyokimyager, kimya mühendisi, biyolog veya mikrobiyolog…',
    'h1' => 'Sorumlu Teknik Eleman',
    'ust' => '/uts/',
    'og' => '/wp-content/uploads/2022/01/utsbackground-3.jpg',
    'ogType' => 'website',
    'yayin' => '2022-01-13T19:21:29+00:00',
    'guncel' => '2022-01-20T17:48:38+00:00',
  ],
  '/uts/kozmetik-urun-bildirimi/' => [
    'title' => 'Kozmetik Ürün Bildirimi - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Bir kozmetik ürün üretip satışa sunacaksanız ya da bir kozmetik ürün ithal edip Türkiye pazarına arz edecekseniz, öncesinde kozmetik kapsamında…',
    'h1' => 'Kozmetik Ürün Bildirimi',
    'ust' => '/uts/',
    'og' => '/wp-content/uploads/2022/01/utsbackground-2.jpg',
    'ogType' => 'website',
    'yayin' => '2022-01-14T09:42:51+00:00',
    'guncel' => '2022-01-20T17:48:48+00:00',
  ],
  '/uts/uts-bilgi-guncelleme/' => [
    'title' => 'ÜTS Bilgi Güncelleme - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Özellikle CE sertifikaları (EC certificate) tahditli validasyona sahiptir. Yani belli bir süre sonra geçerliğini yitirir ve yenilenmesi gerekir…',
    'h1' => 'ÜTS Bilgi Güncelleme',
    'ust' => '/uts/',
    'og' => '/wp-content/uploads/2022/01/utsbackground-5.jpg',
    'ogType' => 'website',
    'yayin' => '2022-01-14T09:47:15+00:00',
    'guncel' => '2022-01-20T17:48:55+00:00',
  ],
  '/uts/tibbi-cihaz-uts-gecisi/' => [
    'title' => 'Tıbbi Cihaz ÜTS Geçişi - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Türkiye İlaç ve Tıbbi Cihaz Kurumu tarafından yayımlanan duyuru gereğince, 01.10.2018 tarihi itibariyle de sınıf III ürün gruplarında tekil ürün…',
    'h1' => 'Tıbbi Cihaz ÜTS Geçişi',
    'ust' => '/uts/',
    'og' => '/wp-content/uploads/2022/01/utsbackground-4.jpg',
    'ogType' => 'website',
    'yayin' => '2022-01-14T09:50:57+00:00',
    'guncel' => '2022-01-20T17:48:49+00:00',
  ],
  '/tibbi-cihaz/firma-kaydi/' => [
    'title' => 'Firma Kaydı - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Türkiye Cumhuriyeti sınırları içinde, ilaç ve/veya tıbbi cihaz üretimi, ithalatı, ihracatı yapan veya bir yabancı firmanın Türkiye yetkili temsilcisi…',
    'h1' => 'Firma Kaydı',
    'ust' => '/tibbi-cihaz/',
    'og' => '/wp-content/uploads/2022/01/dBkuxiyYPC-4.jpg',
    'ogType' => 'website',
    'yayin' => '2022-01-19T08:51:42+00:00',
    'guncel' => '2022-01-21T05:04:28+00:00',
  ],
  '/tibbi-cihaz/firma-bilgileri-guncelleme/' => [
    'title' => 'Firma Bilgileri Güncelleme - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'TİTUBB firma kayıt işlemlerinde verilen taahhütname gereği, TİTUBB’daki bilgi-belge değişiklikleri firma veya kurumlar tarafından gecikmeksizin sisteme…',
    'h1' => 'Firma Bilgileri Güncelleme',
    'ust' => '/tibbi-cihaz/',
    'og' => '/wp-content/uploads/2022/01/dBkuxiyYPC-1.jpg',
    'ogType' => 'website',
    'yayin' => '2022-01-19T09:03:02+00:00',
    'guncel' => '2022-01-21T05:02:38+00:00',
  ],
  '/tibbi-cihaz/ubb-e-imza/' => [
    'title' => 'UBB E-İmza - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Nitelikli Elektronik Sertifika’ya(NES) dayanılarak oluşturulan elektronik imza (e-İmza) güvenli elektronik imzadır.',
    'h1' => 'UBB E-İmza',
    'ust' => '/tibbi-cihaz/',
    'og' => '/wp-content/uploads/2022/01/dBkuxiyYPC-3.jpg',
    'ogType' => 'website',
    'yayin' => '2022-01-19T09:07:18+00:00',
    'guncel' => '2022-01-21T05:03:37+00:00',
  ],
  '/tibbi-cihaz/tibbi-cihaz-belge-kaydi/' => [
    'title' => 'Tıbbi Cihaz Belge Kaydı - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Firmaların sisteme kaydının onaylanması için gerekli evraklar: CE Sertifikası, Uygunluk Beyanı, Kullanım Kılavuzu, Etiket Örneği, Ürün Kataloğu, Yetki Belgesi.',
    'h1' => 'Tıbbi Cihaz Belge Kaydı',
    'ust' => '/tibbi-cihaz/',
    'og' => '/wp-content/uploads/2022/01/dBkuxiyYPC-2.jpg',
    'ogType' => 'website',
    'yayin' => '2022-01-19T09:13:08+00:00',
    'guncel' => '2022-01-21T05:04:06+00:00',
  ],
  '/tibbi-cihaz/etiket-duzenleme/' => [
    'title' => 'Etiket Düzenleme - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Tıbbi Cihaz Yönetmeliğinin (93/42/EEC), Vücuda Yerleştirilebilir Aktif Tıbbi Cihazlar Yönetmeliğinin (90/385/EEC) ve Vücut Dışında Kullanılan Tıbbi Tanı…',
    'h1' => 'Etiket Düzenleme',
    'ust' => '/tibbi-cihaz/',
    'og' => '/wp-content/uploads/2022/01/dBkuxiyYPC.jpg',
    'ogType' => 'website',
    'yayin' => '2022-01-19T09:20:55+00:00',
    'guncel' => '2022-01-21T04:57:08+00:00',
  ],
  '/saglik-bakanligi-islemleri/ilac-ruhsatlandirma/' => [
    'title' => 'İlaç Ruhsatlandırma - Egefe Sağlık Bilişim A.Ş.',
    'desc' => '02.11.2011 tarihli ve 28103 sayılı Resmi Gazetede yayımlanan “Sağlık Bakanlığı ve Bağlı Kuruluşlarının Teşkilat ve Görevleri Hakkında Kanun Hükmünde…',
    'h1' => 'İlaç Ruhsatlandırma',
    'ust' => '/saglik-bakanligi-islemleri/',
    'og' => '/wp-content/uploads/2022/01/utsbackground-16.jpg',
    'ogType' => 'website',
    'yayin' => '2022-01-19T10:06:57+00:00',
    'guncel' => '2022-01-21T06:46:41+00:00',
  ],
  '/saglik-bakanligi-islemleri/ilac-varyasyon/' => [
    'title' => 'İlaç Varyasyon - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Güncel varyasyon kılavuzu doğrultusunda varyasyon kapsamının (Tip IA, Tip IB, Tip II) belirlenmesi ve varyasyon dosyasının hazırlanması',
    'h1' => 'İlaç Varyasyon',
    'ust' => '/saglik-bakanligi-islemleri/',
    'og' => '/wp-content/uploads/2022/01/utsbackground-15.jpg',
    'ogType' => 'website',
    'yayin' => '2022-01-19T10:07:17+00:00',
    'guncel' => '2022-01-21T06:39:20+00:00',
  ],
  '/saglik-bakanligi-islemleri/ilac-fiyatlandirma/' => [
    'title' => 'İlaç Fiyatlandırma - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Avrupa Birliği (AB) üyeleri arasından en az 5, en fazla 10 ülke referans ülke olarak Sağlık Bakanlığınca belirlenir ve bir tebliğle duyurulur.',
    'h1' => 'İlaç Fiyatlandırma',
    'ust' => '/saglik-bakanligi-islemleri/',
    'og' => '/wp-content/uploads/2022/01/utsbackground-17.jpg',
    'ogType' => 'website',
    'yayin' => '2022-01-19T10:07:49+00:00',
    'guncel' => '2022-01-21T06:50:51+00:00',
  ],
  '/saglik-bakanligi-islemleri/biyosidal-ruhsatlandirma/' => [
    'title' => 'Biyosidal Ruhsatlandırma - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Kimyasal veya biyolojik açıdan herhangi bir zararlı organizma üzerinde kontrol edici etki gösteren veya hareketini kısıtlayan, zararsız kılan, yok eden…',
    'h1' => 'Biyosidal Ruhsatlandırma',
    'ust' => '/saglik-bakanligi-islemleri/',
    'og' => '/wp-content/uploads/2022/01/utsbackground-18.jpg',
    'ogType' => 'website',
    'yayin' => '2022-01-19T10:08:37+00:00',
    'guncel' => '2022-01-21T06:55:02+00:00',
  ],
  '/saglik-bakanligi-islemleri/gmp-basvurusu/' => [
    'title' => 'GMP Başvurusu - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Bilindiği üzere 01.03.2010 tarihinden itibaren yapılan CTD ruhsat başvurularında ön inceleme sırasında Bakanlığımızca denetlenerek verilmiş olan GMP…',
    'h1' => 'GMP Başvurusu',
    'ust' => '/saglik-bakanligi-islemleri/',
    'og' => '/wp-content/uploads/2022/01/utsbackground-19.jpg',
    'ogType' => 'website',
    'yayin' => '2022-01-19T10:09:17+00:00',
    'guncel' => '2022-01-21T06:57:34+00:00',
  ],
  '/saglik-bakanligi-islemleri/kub-kt/' => [
    'title' => 'KÜB/KT - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Farmakolojik Değerlendirme Birimi’ne yapılacak tüm başvurularla ( ruhsatlı ürünler için ilk başvuru veya cevap) ilgili olarak; 03.04.2017 tarihinden…',
    'h1' => 'KÜB/KT',
    'ust' => '/saglik-bakanligi-islemleri/',
    'og' => '/wp-content/uploads/2022/01/utsbackground-14.jpg',
    'ogType' => 'website',
    'yayin' => '2022-01-19T10:09:55+00:00',
    'guncel' => '2022-01-21T06:43:49+00:00',
  ],
  '/saglik-bakanligi-islemleri/okunabilirlik-testi/' => [
    'title' => 'Okunabilirlik Testi - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Bilindiği üzere; 25.04.2017 tarih ve 30048 sayılı Resmi Gazetede yayımlanarak yürürlüğe giren Beşeri Tıbbi Ürünlerin Ambalaj Bilgileri, Kullanma Talimatı…',
    'h1' => 'Okunabilirlik Testi',
    'ust' => '/saglik-bakanligi-islemleri/',
    'og' => '/wp-content/uploads/2022/01/utsbackground-6.jpg',
    'ogType' => 'website',
    'yayin' => '2022-01-19T10:10:50+00:00',
    'guncel' => '2022-01-21T05:17:49+00:00',
  ],
  '/diger-hizmetler/permi-belgesi/' => [
    'title' => 'Permi Belgesi - Egefe Sağlık Bilişim A.Ş.',
    'desc' => '2018/4 sayılı Sağlık Bakanlığının Özel İznine Tabi Maddelerin İthalat Denetimi Tebliği kapsamında yer alan; Uyuşturucu ve Psikotrop madde yapımında…',
    'h1' => 'Permi Belgesi',
    'ust' => '/diger-hizmetler/',
    'og' => '/wp-content/uploads/2022/01/utsbackground-22.jpg',
    'ogType' => 'website',
    'yayin' => '2022-01-19T10:17:56+00:00',
    'guncel' => '2022-01-21T07:12:45+00:00',
  ],
  '/diger-hizmetler/ce-teknik-dosya-hazirlanmasi/' => [
    'title' => 'CE Teknik Dosya Hazırlanması - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'CE belgesi almak için başvuruda bulunan firmalar CE teknik dosyası hazırlamak zorundadır. Süreç içerisinde danışmanlık hizmetinin alındığı firma, bu…',
    'h1' => 'CE Teknik Dosya Hazırlanması',
    'ust' => '/diger-hizmetler/',
    'og' => '/wp-content/uploads/2022/01/cebelgesi-1.jpg',
    'ogType' => 'website',
    'yayin' => '2022-01-19T10:19:10+00:00',
    'guncel' => '2022-01-21T07:15:52+00:00',
  ],
  '/diger-hizmetler/takviye-edici-gida/' => [
    'title' => 'Takviye Edici Gıda - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Takviye edici gıda normal beslenmeyi takviye etmek amacıyla; vitamin, mineral, protein, karbonhidrat, lif, yağ asidi, amino asit gibi besin ögelerinin…',
    'h1' => 'Takviye Edici Gıda',
    'ust' => '/diger-hizmetler/',
    'og' => '/wp-content/uploads/2022/01/utsbackground-20.jpg',
    'ogType' => 'website',
    'yayin' => '2022-01-19T10:19:42+00:00',
    'guncel' => '2022-01-21T07:03:17+00:00',
  ],
  '/diger-hizmetler/kontrol-belgesi/' => [
    'title' => 'Kontrol Belgesi - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'İlgili tebliğde bulunan listelerde yer alan maddelerin, karşılarında belirtilen amaçlarla kullanılmak üzere ithal edilmeleri halinde, insan sağlığı ve…',
    'h1' => 'Kontrol Belgesi',
    'ust' => '/diger-hizmetler/',
    'og' => '/wp-content/uploads/2022/01/utsbackground-21.jpg',
    'ogType' => 'website',
    'yayin' => '2022-01-19T10:20:22+00:00',
    'guncel' => '2022-01-21T07:11:59+00:00',
  ],
  '/eroin-bagimliligi/' => [
    'title' => 'Eroin Bağımlılığı - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Eroin Bağımlılığı... Bağımlılık, kişinin fiziksel ve psikolojik birçok zarar görmesine rağmen bağımlısı olduğu maddeyi kullanması, kendinde yol açtığı sıkıntılara karşı bu maddeden vazgeçememesi olarak tanımlanabilir.',
    'h1' => 'Eroin Bağımlılığı',
    'ust' => '/blog/',
    'og' => '/wp-content/uploads/2022/03/AdobeStock_210694690-scaled-1.jpeg',
    'ogType' => 'article',
    'yayin' => '2022-03-26T12:55:03+00:00',
    'guncel' => null,
  ],
  '/eroin-nedir/' => [
    'title' => 'Eroin Nedir? - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Eroin Nedir? Eroin ilk olarak Londra’da bir İngiliz kimyacı tarafından sentezlenmiştir. O zamanlarda morfin çeşitli asitler ile birleştirilerek çeşitli deneyler yapılmaktaydı....',
    'h1' => 'Eroin Nedir?',
    'ust' => '/blog/',
    'og' => '/wp-content/uploads/2022/03/bg-2.jpg',
    'ogType' => 'article',
    'yayin' => '2022-03-26T12:38:47+00:00',
    'guncel' => null,
  ],
  '/opiatlar-nedir/' => [
    'title' => 'Opiatlar Nedir? - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Opiatlar Nedir?',
    'h1' => 'Opiatlar Nedir?',
    'ust' => '/blog/',
    'og' => '/wp-content/uploads/2022/03/61fa241ad265a211742e9f29.jpg',
    'ogType' => 'article',
    'yayin' => '2022-03-26T12:30:20+00:00',
    'guncel' => null,
  ],
  '/kokain-bagimliligi-tedavisi/' => [
    'title' => 'Kokain Bağımlılığı Tedavisi - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Kokain Bağımlılığı Tedavisi... Bağımlılık alkol, uyuşturucu veya uyarıcı bir maddenin kişiye fiziksel, ruhsal ve sosyal sorunlara yol açmasına rağmen kişinin bu maddeleri kullanmaya devam etmesi, bırakma isteğine karşı kullandığı maddeyi bırakamaması ve madde alma isteğini durduramaması olarak tanımlanabilir.',
    'h1' => 'Kokain Bağımlılığı Tedavisi',
    'ust' => '/blog/',
    'og' => '/wp-content/uploads/2022/03/bagimlilik-tedavi-hekim-terapi-madde-danismanlik-1024x1024-1.jpg',
    'ogType' => 'article',
    'yayin' => '2022-03-26T12:20:37+00:00',
    'guncel' => null,
  ],
  '/uyusturucu-testi-nedir/' => [
    'title' => 'Uyuşturucu Testi Nedir? - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Uyuşturucu Testi Nedir?',
    'h1' => 'Uyuşturucu Testi Nedir?',
    'ust' => '/blog/',
    'og' => '/wp-content/uploads/2022/03/csm_content_mpu_test_9d23debc60.jpg',
    'ogType' => 'article',
    'yayin' => '2022-03-19T20:15:37+00:00',
    'guncel' => null,
  ],
  '/kokain-bagimliligi/' => [
    'title' => 'Kokain Bağımlılığı - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Kokain Bağımlılığı... okain uyuşturucu ve uyarıcı maddeler arasında en fazla bağımlılık yapan ve en tehlikeli olan uyarıcı maddelerden biridir.',
    'h1' => 'Kokain Bağımlılığı',
    'ust' => '/blog/',
    'og' => '/wp-content/uploads/2022/03/What-Are-the-Worlds-Most-Dangerous-Drugs.jpg',
    'ogType' => 'article',
    'yayin' => '2022-03-15T15:51:16+00:00',
    'guncel' => '2022-03-18T08:06:18+00:00',
  ],
  '/uyarici-madde-nedir/' => [
    'title' => 'Uyarıcı Madde Nedir? - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Uyarıcı Madde Nedir?',
    'h1' => 'Uyarıcı Madde Nedir?',
    'ust' => '/blog/',
    'og' => '/wp-content/uploads/2022/03/amphetamine-v-methampheta.jpg',
    'ogType' => 'article',
    'yayin' => '2022-03-03T10:51:20+00:00',
    'guncel' => '2022-03-17T08:35:44+00:00',
  ],
  '/esrar-bagimliligi-tedavisi/' => [
    'title' => 'Esrar Bağımlılığı Tedavisi - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Esrar Bağımlılığı Tedavisi...',
    'h1' => 'Esrar Bağımlılığı Tedavisi',
    'ust' => '/blog/',
    'og' => '/wp-content/uploads/2022/03/ot.jpg',
    'ogType' => 'article',
    'yayin' => '2022-03-02T13:39:30+00:00',
    'guncel' => '2022-03-17T08:35:39+00:00',
  ],
  '/esrar-bagimliligi/' => [
    'title' => 'Esrar Bağımlılığı - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Esrar Bağımlılığı...',
    'h1' => 'Esrar Bağımlılığı',
    'ust' => '/blog/',
    'og' => '/wp-content/uploads/2022/03/104607917_gettyimages-1052403286.jpg',
    'ogType' => 'article',
    'yayin' => '2022-03-02T11:00:34+00:00',
    'guncel' => '2022-03-17T08:35:34+00:00',
  ],
  '/esrar-nedir/' => [
    'title' => 'Esrar Nedir? - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Esrar Nedir? İçeriği gibi birçok içerik bilgi içeriği için tıklayınız...',
    'h1' => 'Esrar Nedir?',
    'ust' => '/blog/',
    'og' => '/wp-content/uploads/2022/03/d-1-750x500-1.jpg',
    'ogType' => 'article',
    'yayin' => '2022-03-02T09:24:44+00:00',
    'guncel' => '2022-03-17T08:35:26+00:00',
  ],
  '/trafik-guvenligini-tehlikeye-sokma-sucu/' => [
    'title' => 'Trafik Güvenliğini Tehlikeye Sokma Suçu - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Trafik Güvenliğini Tehlikeye Sokma Suçu',
    'h1' => 'Trafik Güvenliğini Tehlikeye Sokma Suçu',
    'ust' => '/blog/',
    'og' => '/wp-content/uploads/2022/03/Incidente-stradale-sotto-effetto-di-stupefacenti.jpg',
    'ogType' => 'article',
    'yayin' => '2022-03-01T15:47:37+00:00',
    'guncel' => '2022-03-17T08:35:21+00:00',
  ],
  '/alkolmetre-nedir/' => [
    'title' => 'Alkolmetre Nedir? - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Alkolmetre Nedir?',
    'h1' => 'Alkolmetre Nedir?',
    'ust' => '/blog/',
    'og' => '/wp-content/uploads/2022/02/TorontoDUI__Apr_17_post_upd.jpg.500x333_q85_crop.jpg',
    'ogType' => 'article',
    'yayin' => '2022-02-25T13:35:06+00:00',
    'guncel' => '2022-03-17T08:35:12+00:00',
  ],
  '/uyusturucu-madde-testi/' => [
    'title' => 'Uyuşturucu Madde Testi - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Uyuşturucu Madde Testi... Uyuşturucu madde testi bir diğer adıyla drug test olarak bilinmektedir. Uyuşturucu madde testleri kişinin yeşil reçeteli bir ilaca veya uyuşturucu bir madde alıp almadığını tespit etmektedir.',
    'h1' => 'Uyuşturucu Madde Testi',
    'ust' => '/blog/',
    'og' => '/wp-content/uploads/2022/02/closeup-shot-white-pills-glass-dish-lab.jpg',
    'ogType' => 'article',
    'yayin' => '2022-02-22T10:47:21+00:00',
    'guncel' => '2022-03-17T08:35:06+00:00',
  ],
  '/promil-nedir/' => [
    'title' => 'Promil Nedir? - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Promil Nedir?',
    'h1' => 'Promil Nedir?',
    'ust' => '/blog/',
    'og' => '/wp-content/uploads/2022/02/Aday-surucu-alkollu-arac-kullanma-cezasi-1-700x470-1.jpg',
    'ogType' => 'article',
    'yayin' => '2022-02-15T15:07:40+00:00',
    'guncel' => '2022-03-17T08:34:52+00:00',
  ],
  '/kokain-nedir/' => [
    'title' => 'Kokain Nedir? - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Kokain Nedir? Kokain bilinen bir diğer ismi ile benzoylemetil ekgonin, Güney Amerikada yetişen koka bitkisinin yapraklarında elde edilmektedir.',
    'h1' => 'Kokain Nedir?',
    'ust' => '/blog/',
    'og' => '/wp-content/uploads/2022/03/cocaineaddiction.jpg',
    'ogType' => 'article',
    'yayin' => '2022-03-09T14:30:31+00:00',
    'guncel' => '2022-03-17T08:34:09+00:00',
  ],
  '/ergenlerde-uyusturucu-kullanimi/' => [
    'title' => 'Ergenlerde Uyuşturucu Kullanımı - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Ergenlerde Uyuşturucu Kullanımı... Bağımlılık; Bir uyuşturucu maddenin kişi üzerinde fiziksel, ruhsal, ekonomik ve sosyal sorunlara yol açmasına rağmen,  madde alımının yapılması, bırakma arzusuna karşılık kullanıma devam etmek ve maddeyi alma isteğinin durdurulamaması olarak tanımlanabilir',
    'h1' => 'Ergenlerde Uyuşturucu Kullanımı',
    'ust' => '/blog/',
    'og' => '/wp-content/uploads/2022/02/man-overdosed-with-medicine-2.jpg',
    'ogType' => 'article',
    'yayin' => '2022-02-18T09:10:31+00:00',
    'guncel' => null,
  ],
  '/alkol-bagimliligi/' => [
    'title' => 'ALKOL BAĞIMLILIĞI - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'ALKOL BAĞIMLILIĞI',
    'h1' => 'ALKOL BAĞIMLILIĞI',
    'ust' => '/blog/',
    'og' => '/wp-content/uploads/2022/02/tired-young-businessman-drinking.jpg',
    'ogType' => 'article',
    'yayin' => '2022-02-16T11:18:18+00:00',
    'guncel' => null,
  ],
  '/madde-bagimliligi-nedir/' => [
    'title' => 'Madde Bağımlılığı Nedir? - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Madde Bağımlılığı Nedir?',
    'h1' => 'Madde Bağımlılığı Nedir?',
    'ust' => '/blog/',
    'og' => '/wp-content/uploads/2022/02/pills-stethoscope-syringe.jpg',
    'ogType' => 'article',
    'yayin' => '2022-02-15T13:43:16+00:00',
    'guncel' => '2022-02-16T08:30:10+00:00',
  ],
  '/madde-bagimliligi-tedavisi/' => [
    'title' => 'Madde Bağımlılığı Tedavisi - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Madde Bağımlılığı Tedavisi',
    'h1' => 'Madde Bağımlılığı Tedavisi',
    'ust' => '/blog/',
    'og' => '/wp-content/uploads/2022/02/flat-lay-pills-jar.jpg',
    'ogType' => 'article',
    'yayin' => '2022-02-15T16:42:21+00:00',
    'guncel' => '2022-02-16T08:29:49+00:00',
  ],
  '/alkollu-arac-kullanmak/' => [
    'title' => 'Alkollü Araç Kullanmak - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Alkollü Araç Kullanmak',
    'h1' => 'Alkollü Araç Kullanmak',
    'ust' => '/blog/',
    'og' => '/wp-content/uploads/2022/02/dangerous-female-driver.jpg',
    'ogType' => 'article',
    'yayin' => '2022-02-16T08:23:48+00:00',
    'guncel' => '2022-02-16T08:29:41+00:00',
  ],
  '/ekstazi-nedir/' => [
    'title' => 'Ekstazi Nedir? - Egefe Sağlık Bilişim A.Ş.',
    'desc' => '3,4-metilenedioksi-N-metilamfetamin (MDMA) veya bilinen adlarıyla ekstazi, XTC, X, bir tür psikoaktif madde. Kimyasal formülü C11H15NO2 şeklindedir.',
    'h1' => 'Ekstazi Nedir?',
    'ust' => '/blog/',
    'og' => '/wp-content/uploads/2022/01/60894852_2113963838716411_3978326419854852096_n.jpg',
    'ogType' => 'article',
    'yayin' => '2022-01-31T09:28:14+00:00',
    'guncel' => null,
  ],
  '/metamfetamin-nedir/' => [
    'title' => 'Metamfetamin Nedir? - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Metamfetamin (kristal meth); uyarıcı ve halüsinasyon özelliği olan sentetik bir maddedir. Birçok uyarıcı gibi, 6-24 saat süren güçlü bir öfori; dolayısıyla',
    'h1' => 'Metamfetamin Nedir?',
    'ust' => '/blog/',
    'og' => '/wp-content/uploads/2022/01/kapak_103737.jpg',
    'ogType' => 'article',
    'yayin' => '2022-01-31T09:22:12+00:00',
    'guncel' => null,
  ],
  '/amfetamin-nedir/' => [
    'title' => 'Amfetamin Nedir? - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'Amfetamin (alfa-metil-fenetilamin) narkolepsi ve dikkat eksikliği ve hiperaktivite bozukluğu dahil çeşitli bozuklukların tedavisinde, kilo kontrolünde, iştah',
    'h1' => 'Amfetamin Nedir?',
    'ust' => '/blog/',
    'og' => '/wp-content/uploads/2022/01/amfetamin-nedir-amdetamin-ne-icin-kullanilir-amfetamin-kullanmak-suc-mu.jpg',
    'ogType' => 'article',
    'yayin' => '2022-01-31T09:17:16+00:00',
    'guncel' => null,
  ],
  '/kvkk/' => [
    'title' => 'KVKK Aydınlatma Metni - Egefe Sağlık Bilişim A.Ş.',
    'desc' => '6698 sayılı KVKK kapsamında Egefe Bilişim Sağlık San. ve Tic. A.Ş. tarafından web sitesi formları aracılığıyla işlenen kişisel verilere ilişkin aydınlatma metni.',
    'h1' => 'KVKK Aydınlatma Metni',
    'ust' => null,
    'og' => '/wp-content/uploads/2022/01/faceb.jpg',
    'ogType' => 'website',
    'yasal' => true,
  ],
  '/gizlilik-politikasi/' => [
    'title' => 'Gizlilik ve Çerez Politikası - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'ege-fe.com gizlilik ve çerez politikası: toplanan veriler, kullanım amaçları, çerezler, saklama, üçüncü taraflar ve haklarınız.',
    'h1' => 'Gizlilik ve Çerez Politikası',
    'ust' => null,
    'og' => '/wp-content/uploads/2022/01/faceb.jpg',
    'ogType' => 'website',
    'yasal' => true,
  ],
  '/urunler/' => [
    'title' => 'Ürünler - Egefe Sağlık Bilişim A.Ş.',
    'desc' => 'NAM-07 ve NAM-19 delil sınıfı alkolmetreler (Armas Elektronik yetkili bayi ve servisi) ve Egefe\'nin yerli üretim uyuşturucu test kiti markası CROM TEST.',
    'h1' => 'Ürünler',
    'ust' => null,
    'og' => '/img/urun/nam19-saha.webp',
    'ogType' => 'website',
  ],
  '/404/' => [
    'title' => 'Sayfa Bulunamadı - Egefe Sağlık Bilişim A.Ş.',
    'desc' => '',
    'h1' => 'Sayfa bulunamadı',
    'ust' => null,
    'og' => '/wp-content/uploads/2022/01/faceb.jpg',
    'ogType' => 'website',
    'noindex' => true,
  ],
];
