<?php
// ÜRETİLDİ: tools/build.mjs
$yol = '/diger-hizmetler/kontrol-belgesi/';
require __DIR__ . '/../../inc/header.php';
?>
<div class="kap icerik-duzen">
  <article class="metin">
    <figure class="banner"><img src="/wp-content/uploads/2022/01/Basliksiz-1.jpg" alt="Kontrol Belgesi" width="1000" height="666" decoding="async"></figure>
<h4>Sağlık Bakanlığınca Denetlenen Ürünlerin İthalat Denetimi</h4>
<ul><li>İlgili tebliğde bulunan listelerde yer alan maddelerin, karşılarında belirtilen amaçlarla kullanılmak üzere ithal edilmeleri halinde, insan sağlığı ve güvenliği yönünden uygunluğu; <em>Ek – 1 / A-B-C ve Ek – 2 listelerinde yer alan ürünler için <strong>Kontrol Belgesi</strong>, Ek – 3 listesinde yer alan ürünler için <strong>Kontrol Belgesi</strong>ve akabinde <strong>Uygunluk Yazısı</strong> ile belgelenir.</em></li><li>Kontrol belgesinin süresi 12 aydır.</li><li>Ek – 1/A listesinde yer alan 30.03 ve 30.04 Gümrük Tarife İstatistik Pozisyonlu ürünler için yapılan başvuruların Sağlık Bakanlığı tarafından incelenmesi sonucunda özel izin alınması gereken ürünler arasında olduğu tespit edilen ürünler için<em>,“</em><em>Sağlık Bakanlığı’nın Özel İznine Tabi Maddelerin İthalat Denetimi Tebliği (Ürün Güvenliği ve Denetimi: 2012/4)”</em>hükümleri uygulanır.</li><li>Ek – 3 listesinde yer alan ürünlerin ithalatında;</li><li>Ürün gümrüğe gelmeden önce Kontrol Belgesi düzenlenir.</li><li>Ürün gümrüğe geldikten sonra, gümrüğe en yakın İl Sağlık Müdürlüğü personeli tarafından numune alınıp Refik Saydam Hıfzıssıhha Merkezi Başkanlığı veya en yakın Bölge Hıfzıssıhha Enstitü Müdürlüğüne teslim edilir. Laboratuvar analiz sonucunun ilgili mevzuata uygun bulunması halinde İl Sağlık Müdürlüğü tarafından Uygunluk Yazısı düzenlenir.</li><li>Analiz sonucuna göre ürünün ilgili mevzuatına uygun olmadığının tespiti halinde, İl Sağlık Müdürlüğünce gerekçeli Uygunsuzluk Yazısı düzenlenir.</li></ul>
<h2>Kontrol Belgesi Başvurusu İçin Gerekli Belgeler</h2>
<ul><li>Başvuru dilekçesi (Örneği tarafımızca gönderilecektir)</li><li>Kontrol belgesi formu (3 Nüsha – Örneği tarafımızca gönderilecektir)</li><li>Proforma fatura veya fatura</li><li>Analiz sertifikası</li><li>Menşe ülkenin yetkili mercii tarafından onaylı sağlık sertifikası ve tercümesi</li><li>Kontrol belgesi verilmiş bir ürün ile aynı menşe ülke ve ihracatçı firmaya ait, aynı spesifikasyonlara sahip ürünün müteakip ithalatlarında, daha önce alınan kontrol belgesi için Sağlık Bakanlığı’na sunulan sağlık sertifikasına göre işlem yapılır. Ancak, Bakanlıkça gerek görülmesi halinde sağlık sertifikasının yenilenmesi istenebilir.</li><li>Doğrudan tüketiciye intikal eden maddelerin ithalatında, gerekli görülen durumlarda aşağıda yer alan bilgilerin Sağlık Bakanlığı’na ibrazı gerekir.</li></ul>
<ol><li>İthalatçı firmanın unvanı ve adresi</li><li>Malın imal tarihi, muhafaza şartları, seri no, muhteviyatı, kullanma talimatı ve özellikleri</li><li>Süreli mallarda son kullanma tarihi</li><li>Kullanım amacı ve günlük dozu</li></ol>
<ul><li>Avrupa Birliği’nde serbest dolaşıma girmiş, Birliğin mevzuatına göre üretilen ve belgelendirilen ürünlere ilişkin bilgi, belge, test ve analiz sonuçlarının Bakanlığa iletilmesi halinde ürünün özelliğine göre Bakanlıkça doğrudan <em>kontrol belgesi</em> ve/veya uygunluk yazısı verilir. Ancak, ülke koşulları göz önüne alınarak, ilave bilgi ve belgeler istenebilir, ithale konu ürün fiziki muayene ve teste tabi tutulabilir.</li><li>İlaç sanayiinde kullanılan tıbbi müstahzarların terkibinde bulunan ilaç ham başlangıç maddelerini ve ilaç hammaddeleri üretiminde kullanılan maddeleri ithal eden ilaç sanayicisi veya ilaç sanayicisi adına ithalat yapan tedarikçilerin, ithalatın gerçekleşmesinden sonra en geç 15 gün içinde gümrük beyannamesi örneği ve Bilgi Formunu (Örneği tarafımızca gönderilecektir) Sağlık Bakanlığına (İlaç ve Eczacılık Genel Müdürlüğü) iletmesi zorunludur.</li></ul>
<ul><li>Başvuru dilekçesi (Örneği tarafımızca gönderilecektir) Kontrol belgesi formu (3 Nüsha – Örneği tarafımızca gönderilecektir) Proforma fatura veya fatura Analiz sertifikası Menşe ülkenin yetkili mercii tarafından onaylı sağlık sertifikası ve tercümesi Kontrol belgesi verilmiş bir ürün ile aynı menşe ülke ve ihracatçı firmaya ait, aynı spesifikasyonlara sahip ürünün müteakip ithalatlarında, daha önce alınan kontrol belgesi için Sağlık Bakanlığı’na sunulan sağlık sertifikasına göre işlem yapılır. Ancak, Bakanlıkça gerek görülmesi halinde sağlık sertifikasının yenilenmesi istenebilir. Doğrudan tüketiciye intikal eden maddelerin ithalatında, gerekli hallerde aşağıda belirtilen bilgilerin Sağlık Bakanlığı’na sunulması gerekir. İthalatçı firmanın unvanı ve adresi Malın imal tarihi, muhafaza şartları, seri no, muhteviyatı, kullanma talimatı ve özellikleri Süreli mallarda son kullanma tarihi Kullanım amacı ve günlük dozu</li></ul>
<h2>Kontrole Tabi Maddelerin İthaline Mahsus Ruhsatname:</h2>
<ul><li>Ek – 1 sayılı listede yer alan madde ve müstahzarları ithal edenler, ithalatın gerçekleşmesinden sonra en geç 15 gün içinde, Sağlık Bakanlığı’nca verilen, kullanım süresi 6 ay olan <strong>Kontrole Tabi Maddelerin İthaline Mahsus Ruhsatname</strong>nin gümrüklerce onaylı <strong>“D”</strong>nüshasını ve ilgili gümrük beyannamesi örneğini Bakanlığa (İlaç ve Eczacılık Genel Müdürlüğü) göndermekle yükümlüdür. Aynı ruhsatnamenin bir suretinin mala refakat etmesi zorunludur.</li><li>Ek – 1 sayılı listede yer alan ve <em>Uyuşturucu ve Psikotrop Maddelerin Kaçakçılığına Karşı 1988 Birleşmiş Milletler Sözleşmesi</em> kapsamında olup, Sağlık Bakanlığı’nca düzenlenen Kontrole Tabi Maddelerin İthaline Mahsus Ruhsatname ile ithalatçı tarafından gümrüğe getirilen kimyasal madde / narkotik prekürsörlerin ithalatında, Sağlık Bakanlığı’nca düzenlenen ve bir yıl geçerli <em>Kontrole Tabi Kimyasal Maddelerin Fiili İthalatında Gümrük İdarelerinde Kullanılmaya Mahsus Kayıt Belgesi </em>aranır.</li></ul>
<p>İthalatçı veya temsilcisi, ithalatın gerçekleşmesinden sonra en geç 15 gün içinde gümrüklerce onaylanmış belgenin aslı, ilgili gümrük beyannamesi örneği, fatura ve dağıtıcı firma tarafından ithalatçı firmaya düzenlenen ve ithalatın hangi ruhsatnameye istinaden gerçekleştirildiğini gösteren belgeyi Sağlık Bakanlığı’na (İlaç ve Eczacılık Gen. Müd.) iletmekle yükümlüdür.</p>
<h2>Kapsam Dışı Yazısı:</h2>
<p>Gümrük Taife İstatistik Pozisyonu itibariyle Ek-1 sayılı listede yer alan ancak, özel izne tabi olmayan ürünler için Bakanlıkça <em>Kapsam Dışı Yazısı</em> düzenlenerek ilgili gümrük idaresine iletilir. Bu ürünlerin Sağlık Bakanlığınca Denetlenen Bazı Ürünlerin İthalat Denetimi Tebliği (Ürün Güvenliği ve Denetimi: 2012/20) dâhil başka bir mevzuat kapsamına girmesi halinde ilgili mevzuat hükümleri uygulanır.</p>
  </article>
  <?php $hub = '/diger-hizmetler/'; require __DIR__ . '/../../inc/kenar-hizmet.php'; ?>
</div>
<?php require __DIR__ . '/../../inc/cta.php'; ?>
<?php require __DIR__ . '/../../inc/footer.php'; ?>
