<?php
// ÜRETİLDİ: tools/build.mjs
$yol = '/ekstazi-nedir/';
require __DIR__ . '/../inc/header.php';
?>
<div class="kap kap-dar">
  <article class="metin yazi">
    <p class="yazi-bilgi"><a href="/category/saglik/">Sağlık</a></p><!-- yayın tarihi görünmez (kullanıcı kararı 2026-10-01); JSON-LD'de durur -->
    <figure class="banner"><img src="/wp-content/uploads/2022/01/60894852_2113963838716411_3978326419854852096_n.webp" alt="Ekstazi Nedir?" width="731" height="420" decoding="async"></figure>
<p>3,4-metilenedioksi-N-metilamfetamin (MDMA) veya bilinen adlarıyla ekstazi, XTC, X, bir tür psikoaktif madde. Kimyasal formülü C11H15NO2 şeklindedir.</p>
<p>Ekstazi genellikle üzerinde bir resim ya da logo basılı tablet veya kapsüller halinde bulunur. Çok nadiren toz halde olabilir. Tabletler sürekli değişmekte ve yaygın olarak sahte ya da taklit tabletler satılmaktadır. Böylece marka ismi ve açıklamaları kısa sürede değersiz hale gelmektedir. Analizlere göre tüm ekstazi tabletlerinin yarısı hiç MDMA içermemektedir. Bazı tabletlerin efedrin, amfetamin, ketamin, DXM ve MDMA türevi olan MDA ya da MDEA gibi maddeler içerdiği, diğer bir grubun ise herhangi bir ilaç ya da aktif ajan içermediği bulgulanmıştır.</p>
<h3>Ekstazi Tarihçesi</h3>
<p>İlk kez 1912’de Alman ilaç firması Merck tarafından Darmstadt’ta sentezlendi. İlacın anoreksi tedavisi için ya da iştah baskılayıcı olarak sentezlendiği kanısı 2006’da Roland W. Freudenmann’ın yaptığı araştırmayla netliğe kavuşturuldu.[2] Merck firmasına ait 274350 numaralı patentte diğer birçok ilaçla yeni bir kimyasal yol bulunmasında öncü olan maddenin hemostatik maddeler bulma amaçlı olarak patentlendiği belirtilmektedir. İlaç kanın pıhtılaşmasını sağlayacak bir başka ilaç aranırken bulunan bir ara maddedir. Patentte ismi değil kimyasal açılımıyla belirtilen madde, Merck firması tarafından daha sonraları ilk kez metilsifrilamin olarak anıldı.</p>
<p>Nasıl sentezlendiğini ilk açıklayan kişi Dr. Anton Köllisch’tir. İlaçla ilgili ilk farmakoloji testleri 1927 ve 1952’de, insanlar üzerindeki ilk testler ise bulunduktan çok sonraları, 1960’ta yapıldı. Roland W. Freudenmann’a göre ilacın iştah baskılayıcı amaçlı sentezlendiği yanlış kanısı MDMA analogu olan MDA’in 1949 ve 1957 yılları arasında Smith Kline ve French Laboratuvarları’nda antidepresan ve iştah kapayıcı olarak araştırılmasından kaynaklanmaktadır. İlaçla ilgili ilk toksikoloji testleri 1952’de yapıldı.</p>
<p>MDMA ilk kez 1970’li yıllarda Chicago’da sokaklarda satılan tabletlerde tespit edildi. İlk insan deneyleri her ne kadar 1960’lardan sonra başladıysa da yaygınlaşmasında önemli bir rol oynayan kişi Alexander Shulgin’dir. Shulgin 1976’da sentezleyip denedikten sonra çalışma arkadaşlarıyla birlikte yaptığı kapsamlı araştırmalarında ilacın kimyası, dozajı, kinetiği ve psikoaktif etkileri üzerine ilk ayrıntılı raporları yayınladılar ve ekstazi bu araştırmalardan sonra yaygınlaştı. 1976’da Shulgin ile birlikte ilacın sıradışı teröpötik etkilerini fark eden bir grup bilim adamı ve terapist suistimal edilmesini, sorumsuz ve bilinçsiz kullanımı engellemek için bu ilacı çok kapalı bir grup içinde kullandılar.</p>
<p>Bu araştırma ve tedavi amaçlı çalışmalarda MDMA’in evlilik ve ilişki terapisi, PTSD (travma sonrası stres bozukluğu), travma, fobi bozuklukları, bağımlılık, kanser ve ölümcül hastalıklardan muzdarip kişilerde endişe tedavisinde kullanılabileceği birçok psikiyatrist ve psikoterapist tarafından kabul gördü ve yasaklandığı 1985’e kadar terapilerde yasal olarak kullanıldı. Psikedelikler ile araştırma yapan psikiyatrlardan Stanislav Grof, M. D yasaklamanın meşru bilimsel çalışmaları engellerken yaygın kullanımının önüne geçemediğini belirtmektedir.</p>
<p>Bu terapistlerin “empati” olarak andığı ilacın sokak tabiri olan “ekstazi” adı ise ilk kez 1984’te ABD’nin Kaliforniya eyaletinden çıktı. Shulgin empati adının ilacın etkilerini daha isabetli çağrıştırdığını ekstazinin ise bir pazarlama tekniği olarak kullanıldığını yazmaktadır. Shulgin ve çevresi ilacın suistimale neden olabilecek derecede yaygınlaşmasını engellemek için her ne kadar ketum davransalar da yaygınlaşmasının önüne geçilemedi. Yanlış kullanımdan ötürü yaşanan bazı ölüm vakaları neden gösterilerek ABD’de 1985’te yasaklanan ilacı daha sonra diğer devletler izledi.</p>
<h3>Etkileri</h3>
<p>MDMA beyinde varolan 5-HT (serotonin) nörotransmiterlerinin salınmasını sağlayan bir serotonin ateşleyicisi ve geri alım inhibitörüdür. Antidepresan ilaçlar da aynı sınıftandır ama MDMA’in farkı beyinde varolan serotoninin tamamının salınmasını sağlamasıdır.</p>
<p>Genellikle kişide yarattığı rahatlık, doygunluk, zindelik ve mutluluk hisleri nedeniyle kullanılır. Psikoterapiyi desteklemede ise kişi engellenme ve korku hisleri olmadan rahatça konuşabildiği için kullanılmaktadır. MDMA etkisi altındaki kişi empati yeteneğinde artış, varoluşu ve kendini olduğu gibi kabul edebilme nitelikleri gösterir. Normalde varolan karakter zırhı yumuşar, kişi çekinmeden ve rahatça iletişim kurabilir. Kullananların neredeyse %99’unun olumlu duygularla bağlantıya geçtiği bilinmektedir.</p>
<p>Oral yoldan alındığında yaklaşık 30-40 dakika sonra etkisini göstermeye başlayan ilacın etkileri 3-4 saat sürer. Yapılan araştırmalar kısa dönem hafıza ve iştah kaybı, uykusuzluk, acı eşiğinde yükselme, xerostomi, göz bebeklerinde büyüme ve sağa sola hareketlilik, ısı regülasyonunda bozulma, diş sıkma (bruksizm), erkeklerde sertleşme sorununa (erektil disfonksiyon), kas spazmlarına neden olabileceğini göstermektedir. Bulantı ve kusma gibi kişiye özel etkiler görülebilir ve her kişinin vereceği tepkiler de farklılık gösterebilir.</p>
<p>Aşk ilacı olarak tanınmasının nedeni sevgi, şefkat ve empati duygularında artışa neden olmasıdır. Cinsel arzularda ise artma değil genelde azalma görülür. Kadınlar daha rahat davranabildikleri için samimi yakınlaşmalara daha açık gibi görünürler. Erkeklerde sertleşme sorununa (erektil disfonksiyona) neden olur. Bu nedenle buradaki aşk libidinal (cinsel) anlamda değil şefkat anlamında bir aşktır. Her iki cins için de savunma kalkanlarının indirilmesi fiziksel ve duygusal yakınlaşmayı kolaylaştıran bir ortam yarattığı için ve belki de bir pazarlama tekniği olarak aşk-seks ilacı dendiği düşünülebilir. MDMA etkisi altındaki kişide genelde libidinal (cinsel) dürtüler tamamen ortadan kalkmasa da oldukça azalır.</p>
<h3>Riskleri</h3>
<p>Ekstaziden ölüm vakaları hiç sıvı almadan yüksek dozda ekstazi alıp dinlenmeden aralıksız dans eden, kardiyovasküler sorunları olan ve/veya ekstaziyi başka ilaçlarla karıştıran kişiler arasında görülür. Sıvı kaybına neden olduğu için vücudun kaybettiği oranda sıvı tüketmesi gerektiği bilinmekle birlikte aşırı su tüketiminin de ölüme kadar götürebilecek hiponatremi denilen su zehirlemesine yol açabildiği bilinmektedir. Kadınlar erkeklere oranla hiponatremiye karşı daha hassastırlar. Hiponatremi, dehidratasyon endişesi ile aşırı içilen suyun kanı seyrelterek beynin şişmesine yol açmasıdır. Isı kaybını azaltabilir ve bazen de kasların ve beynin ısı üretimini arttırabilir. Kardiyovasküler (kalp) rahtsızlıkları olan kişiler risk altında olan bir gruptur. Ayrıca mono amin oksidaz (MAO) inhibitörü (MAOI) olarak bilinen ilaçlarla birlikte kullanılması “hipertansiyon krizi” denilen ve kalbin tehlikeli derecede hızlı çarpmasıyla kendini gösteren ölümcül bir komplikasyona yol açabilir ve tıbbi müdahale olmazsa kişi ölebilir. 1987’den bu yana bu nedenle ölümler rapor edilmiş durumdadır.</p>
<p>SSRI türü antidepresanlar ile birlikte kullanıldığında “serotonin sendromu” denilen rahatsızlığa neden olabilir. Serotonin sendromu, kas spazmları, mide-bağırsak sorunları, ishal, zihin karışıklığı, ajitasyon, koordinasyon bozukluğu, titreme, ateş ve terleme ile kendini gösterir. Araştırmalar henüz yetersiz olduğu için başka hiçbir ilaçla karıştırılmaması kişinin en güvenli konumda olmasını sağlayacaktır.</p>
<p>MDMA diye satılan tabletlerin bazılarında bulunan DXM maddesi SSRI ve NMDA antagonisti özellikleri gösterir ve ekstazi ile karıştırıldığında “serotonin sendromu” olarak bilinen rahatsızlığa yol açabilir. Dancesafe gibi sivil kuruluşlar kullanıcıların zarar görmemesi için kullanımın yoğun olduğu ortamlarda ilaç içerik ve saflık testi imkânı sağlamaktadır.</p>
<h4>Fiziksel zarar ve bağımlılık derecelerine göre uyuşturucu maddeler</h4>
<p>İlacın etkileri geçtikten sonra yaklaşık sekiz saat daha “after effect” denilen “hafif etkileri” devam eder. Kişi daha sonra kısa veya bazen iki gün ya da günlerce süren bir depresyon, melankoli ya da yoksunluk dönemine girebilir. Bu sürecin ardından kişi tekrar normal konumuna geri döner. Kişilerin normal durumlarına dönmeleri için beslenmeleri, yeterli derecede sıvı almaları, uyumaları ve bozulan kalsiyum, magnezyum, potasyum ve çinko gibi minerallerin dengesini doğru beslenme ya da diyet katkılarıyla onarmaları ve egzersiz yapmaları gerekir. Beslenmeme, uykusuzluk ve kalsiyum, magnezyum, potasyum ve çinko azalmasına bağlı etkiler hassas kişilerde komplikasyonlara neden olabilir. Ayrıca depresyon ve bağımlılık eğilimi olan kişilerin hekim gözetimi olmadan düzenli olarak kullanması da komplikasyonlara neden olabilir.</p>
<h3>Dozaj</h3>
<p>Normalde 120 miligramlık bir doz kişinin tipik ekstazi etkileri hissetmesi için yeterlidir. Yapılan analiz istatistikleri piyasadaki tabletlerde genellikle bunun yarısı ya da daha azı oranında MDMA bulunduğunu göstermiştir. 120 mg’dan daha fazla miktarda alınan dozlar vücudun homeostatik dengesini bozmaktan başka bir işe yaramaz, daha “iyi” ya da daha kuvvetli etkiler sağlamaz. Araştırılmasına izinlerin yeni verilmeye başlandığı için düzenli bir kullanımın uzun dönemde nasıl etkilere neden olacağı tam olarak bilinmemektedir.</p>
<p>Ekstazi Test Cihazı için tıklayın.</p>
<p>Diğer bilgiler için <a href="https://www.google.com/search?q=Ekstazi&amp;source=lmns&amp;bih=568&amp;biw=1366&amp;hl=tr&amp;sa=X&amp;ved=2ahUKEwiMjLT81dv1AhVeiP0HHaI0CpUQ_AUoAHoECAEQAA" target="_blank" rel="noopener">tıklayın</a>.</p>
  </article>
  <?php $markaTur = 'kutu'; require __DIR__ . '/../inc/marka-crom.php'; ?>
  <nav class="yazi-gezinme" aria-label="Diğer yazılar">
    <a class="onceki" href="/metamfetamin-nedir/"><span>Önceki yazı</span>Metamfetamin Nedir?</a>
    <a class="sonraki" href="/madde-bagimliligi-nedir/"><span>Sonraki yazı</span>Madde Bağımlılığı Nedir?</a>
  </nav>
</div>
<?php require __DIR__ . '/../inc/cta.php'; ?>
<?php require __DIR__ . '/../inc/footer.php'; ?>
