<?php
// ÜRETİLDİ: tools/build.mjs
$yol = '/eroin-bagimliligi/';
require __DIR__ . '/../inc/header.php';
?>
<div class="kap kap-dar">
  <article class="metin yazi">
    <p class="yazi-bilgi"><time datetime="2022-03-26">26 Mart 2022</time> · <a href="/category/saglik/">Sağlık</a></p>
    <figure class="banner"><img src="/wp-content/uploads/2022/03/AdobeStock_210694690-scaled-1.jpeg" alt="Eroin Bağımlılığı" width="1920" height="1080" decoding="async"></figure>
<figure class="gorsel"><img src="/wp-content/uploads/2022/03/methode_sundaytimes_prod_web_bin_02eaa00a-003a-11eb-b722-e6d55bc5f059.jpg" alt="Eroin Bağımlılığı" loading="lazy" decoding="async" width="1920" height="1080"><figcaption>Eroin Bağımlılığı</figcaption></figure>
<p>Bağımlılık, kişinin fiziksel ve psikolojik birçok zarar görmesine rağmen bağımlısı olduğu maddeyi kullanması, kendinde yol açtığı sıkıntılara karşı bu maddeden vazgeçememesi olarak tanımlanabilir. Bağımlılığın dört farklı etmeni vardır. Bunlar; biyolojik, psikolojik, sosyal ve kültürel etmenlerdir. Yani bağımlı olan kişide bu dört etmenin bozuklukları görülebilir.</p>
<p>Eroin uyuşturucu maddeler arasında en tehlikeli maddelerden bir tanesidir. Beyaz, koyu gri, fildişi ve kahverengi tonlarda bulunun eroin, küçük kristaller halinde veya un gibi toz halinde bulunabilir. Afyon çiçeğinden elde edilen eroin maddesinin, etkisi yaklaşık 4 ila 6 saat sürmektedir. Çeşitli kullanım yolları bulunan eroinin, çok tehlikeli olmasının nedenlerinden biri ise damardan enjeksiyon yoluyla kullanım oranının oldukça yüksek olmasıdır. Bu gibi durumlarda fazla dozlar kişide ölüm ile sonlanabilir. Eroinin çeşitli kullanım yolları vardır. Eroin sigaraya sarılarak, ısıtıp buharı koklanarak, burundan veya ağızdan çekilerek kullanılabilir.</p>
<p>Eroin bağımlılık yapma seviyesi oldukça yüksektir. Kişi ilk kullanımdan itibaren bu maddeye ihtiyaç duymakta ve bu süreç ileri düzey bağımlılığa kadar ilerlemektedir. Eroin kişiye ilk kullanımdan itibaren farklı bir zindelik hissi vermektedir. Kullanım yöntemlerinde nişasta, kinin, kargabüken özü gibi tehlikeli zehirlerle karıştırılarak etkisi arttırılmaktadır. Bu gibi kullanımların ardından eroin kişiyi büyük bir zihinsel bulanıklığa sokmaktadır.</p>
<p>Eroin kullanımının ardından kişide düşünce yetisi oldukça zayıflar, bir rahatlama hissiyatı gelir ve solunum yavaşlamaya başlar. İleri düzey bağımlılıklarda ve yüksek dozlarda alındığında vücutta damarlar zedelenmeye başlar, çeşitli deri iltihapları, yaralar ve çıbanlar oluşabilir. Eroin bağımlıların aynı ortamda bulunup hijyensiz şekilde bu maddeyi kullanması sonucu hepatit virüsü oluşabilir. Bu virüs genellikle kişilerin aynı şırıngayı kullanmasından kaynaklanmaktadır.</p>
<p>Eroin bağımlılığı olan bireyler pek çok fiziksel ve ruhsal sıkıntı yaşamaktadırlar. Bunlar;</p>
<ul><li>Çeşitli Spazmlar</li><li>Bitmeyen Halsizlik Hissiyatı</li><li>Kabızlık</li><li>Uyku Problemleri</li><li>Damarlarda Daralma</li><li>Anksiyete</li><li>Depresyon</li><li>Ağız Kuruluğu</li><li>Eklem Ağrıları</li><li>Ciltte yaralar ve kaşıntılar</li><li>Burun iç dokusunda yaralar</li><li>Karaciğer, akciğer ve böbrek hastalıkları</li><li>Denge Sisteminin Bozulması</li><li>Kalp Ritminde Değişimler</li><li>Ani Ruhsal Değişimler</li><li>Gözbebeklerinde Küçülme</li><li>Sosyal Çevre ve Aileden Uzaklaşma</li><li>Maddi Problemler gibi birçok sıkıntıya yol açmaktadır.</li></ul>
<h3>Eroin Kullanımı Nasıl Anlaşılır?</h3>
<figure class="gorsel"><img src="/wp-content/uploads/2022/03/vietnam-heroin-2_wide-9a783ea88fe390516a23a83df5e3bb5c9f66635c.jpg" alt="Eroin Bağımlılığı" loading="lazy" decoding="async" width="1920" height="1079"><figcaption>Eroin Bağımlılığı</figcaption></figure>
<p>Uyuşturucu ve uyarıcı madde kullanımı günümüzde dünyada ve ülkemizde çok büyük bir sorun haline gelmiştir. Gün geçtikçe uyuşturucu ve uyarıcı maddelerin kullanım yaşı düşmekte, uyuşturucu ve uyarıcı maddeler her yaştan bireyi tehdit etmekte ve büyük sorunlar ortaya çıkarmaktadır. Böyle durumlarda bağımlı kişilerin yakınları veya ailelerin şüphelenip sordukları soru şudur eroin kullanan bir bireyi nasıl anlayabiliriz?</p>
<figure class="gorsel"><img src="/wp-content/uploads/2022/03/https___cdn.cnn_.com_cnnnext_dam_assets_160428183940-fentanyl-opioids-drugs-overdose-sanjay-gupta-mobile-orig-mss-00000000.jpg" alt="Eroin Bağımlılığı" loading="lazy" decoding="async" width="1920" height="1080"><figcaption>Eroin Bağımlılığı</figcaption></figure>
<p>Eroin bağımlılarını ve kullanıcılarının genellikle denge sistemlerini etkilemektedir. Buna bağlı olarak bedensel hareketlerde ve yürümede bozukluklar oluşmaktadır. Bu bireyler zamanla sosyal hayatlarında durgun ve isteksiz gözükür. Eroin bağımlılığı çok çabuk geliştiğinden dolayı bireylerde doz alma ihtiyacı sıklaşır buna bağlı olarak ekonomik problemler artar, öz bakım azalır. Eroin kullanıcıları eroine başlangıçlarında solunum yoluyla başlasa bile zamanla daha büyük bir etki istediklerinden dolayı damardan enjeksiyon yoluna başvururlar. Buda Kollarda, kasıklarda, bacak arkalarında iğne izleri oluşturur. Bireyler zamanla kilo kaybına uğrar, gözaltlarında morluklar oluşur ve ten renkleri değişir.</p>
<p>Eroin kullanımından yaklaşık 6 saat içinde idrarda tespit edilebilir. Ancak <a href="https://tr.wikipedia.org/wiki/Opioid" target="_blank" rel="noopener">opioid</a> metabolitlerinin idrardaki tespiti kullanım sonrası 1 ila 3 gün arasındadır. Eroin idrar yoluyla vücuttan atılmaktadır. İdrarın başka tespit edilme yolları ise; saç kılı örneği, kan testi, tırnak testidir. Ayrıca <a href="/">Egefe Bilişim Sağlık</a> ürünü olan Uyuşturucu Test Kiti ve Uyuşturucu Test Cihazı ila eroin kullanımından kısa bir süre sonra test yapılıp, kişinin eroin, uyuşturucu ve uyarıcı maddelerin tespiti yapılabilmektedir.</p>
  </article>
  <nav class="yazi-gezinme" aria-label="Diğer yazılar">
    <a class="onceki" href="/eroin-nedir/"><span>Önceki yazı</span>Eroin Nedir?</a>
    <span></span>
  </nav>
</div>
<?php require __DIR__ . '/../inc/cta.php'; ?>
<?php require __DIR__ . '/../inc/footer.php'; ?>
