<?php
// ÜRETİLDİ: tools/build.mjs
$yol = '/saglik-bakanligi-islemleri/kub-kt/';
require __DIR__ . '/../../inc/header.php';
?>
<div class="kap icerik-duzen">
  <article class="metin">
<h2>KÜB/KT BAŞVURULARI</h2>
<ol><li>Farmakolojik Değerlendirme Birimi’ne yapılacak tüm başvurularla ( ruhsatlı ürünler için ilk başvuru veya cevap) ilgili olarak; 03.04.2017 tarihinden itibaren ekte bulunan “<em>Kısa Ürün Bilgisi</em> (KÜB) ve <em>Kullanma Talimatı</em> (KT) Değerlendirme Başvuru Formu”nun Ruhsat sahibi tarafından doldurularak, diğer dökümanlarla birlikte başvuru dosyasına eklenmesi gerekmektedir. Başvuruya ait üst yazı metninde “Kısa Ürün Bilgisi (KÜB) ve Kullanma Talimatı (KT) <em>Değerlendirme Başvuru Formu</em>”unda beyan edilen tüm bilgilerin doğruluğunun taahhüt edilmesi gerekmektedir. (Varyasyon başvurularında “Ruhsatlandırılmış veya Ruhsatlandırma Başvurusu Yapılmış Beşeri Tıbbi Ürünlerdeki Değişikliğe ait Başvuru Formu” da başvuruya eklenmeye devam edilecektir.)</li><li>Titck İlaç Ruhsatlandırma Dairesi Başkanlığı, Klinik Değerlendirme Biriminde incelemesi devam eden ürünler için; ruhsat sahibi/ruhsat başvuru sahibi firma tarafından Farmakolojik Değerlendirme Birimi’ne eşzamanlı KÜB-KT başvurularının yapılmaması, ürünün Klinik Değerlendirme Biriminde işlemlerinin tamamlanmasının ardından <em>KÜB-KT</em> onayı için Farmakolojik Değerlendirme Birimi ya da Ruhsatlandırma Birimi’ne (ruhsatsız ürünler için) başvurulması gerekmektedir.</li><li>KÜB-KT’de farmakolojik veriler dışında değişikliğe neden olan varyasyonlarla ilgili olarak; ilgili birimden alınmış bir onay varsa ilgiye eklenmesi gerekmektedir. Farmakolojik Değerlendirme Birimi dışındaki birimlere yapılan varyasyon başvuruları onaylanmadan <em>KÜB-KT</em> metinlerine yansıtılmaması ve Farmakolojik Değerlendirme Birimi’ne başvuru yapılmaması gerekmektedir.</li><li>Titck Daire Başkanlığına bağlı tüm birimlere yapılacak, ekinde KÜB-KT yer alan başvurularda; KÜB-KT ve SPC-PIL dosyalarının ayrı dosyalar halinde (renkli KÜB, renkli KT, temiz KÜB, temiz KT, SPC, PIL şeklinde altı ayrı dosya olarak ) elektronik başvuruya eklenmesi, eklenen KÜB-KT dosyalarının resmi web sitemizde yayımlanmaya uygun, alt bilgi-üst bilgi içermeyecek şekilde sunulması gerekmektedir.</li><li>Titck Daire Başkanlığına bağlı tüm birimlere yapılacak başvuruların ekinde yer alan KÜB-KT dosyalarının word formatından PDF formatına dönüştürülerek hazırlanmış olması gerekmektedir.</li><li>Titck Daire Başkanlığına bağlı tüm birimlerle yapılacak KÜB-KT eksik evrak yazışmalarında (referans, literatür talebi vb.) Kurumumuza cevaben gönderilen evrak ekinde Kurum tarafından talep edilen dökümanın yanında, mutlak suretle başvuru sahibince güncelleme talep edilen ve ilk başvuru ekinde yer alan KÜB-KT örneklerinin de sunulması gerekmektedir.</li><li>KÜB-KT hazırlanmasında referans olarak kullanılan dökümanların, orijinal dili İngilizce değilse, başvuru ekinde orijinal yeminli tercümelerinin sunulması gerekmektedir.</li></ol>
  </article>
  <?php $hub = '/saglik-bakanligi-islemleri/'; require __DIR__ . '/../../inc/kenar-hizmet.php'; ?>
</div>
<?php require __DIR__ . '/../../inc/cta.php'; ?>
<?php require __DIR__ . '/../../inc/footer.php'; ?>
